set autoindent
set autoread
set backspace=eol,indent,start
set cursorline
set colorcolumn=80
set encoding=utf-8
set fillchars=vert:│
set hlsearch
set incsearch
set lazyredraw
set list
set listchars=tab:>─,eol:¬,trail:\ ,nbsp:¤
set scrolloff=4
set showmatch
set smartcase
set smarttab
set softtabstop=-1
set splitbelow
set splitright
set wildmenu
set wildmode=longest:full,list:full
syntax enable
syntax on
autocmd Filetype make setlocal noexpandtab
autocmd FileType vim setlocal foldmethod=marker
let g:gutentags_cache_dir = expand('~/.cache/vim/ctags/')

map <silent> <F6> :NERDTreeToggle<CR>
map <C-c> :!xsel -b < %<CR>

" UltiSnips
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<S-tab>"

" Compile and run
autocmd filetype cpp nnoremap <F5> :w<bar>term ++shell g++ %:p -o %:p:r -g -fsanitize=address; %:p:r<CR>
